export const SIGNUP_REQUEST ='SIGNUP_REQUEST';
export const SIGNUP_USER_STARTED ='SIGNUP_USER_STARTED';
export const SIGNUP_USER_SUCCESS ='SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE ='SIGNUP_USER_FAILURE';
export const LOGIN_REQUEST ='LOGIN_REQUEST';
export const LOGIN_STARTED ='LOGIN_STARTED';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILURE ='LOGIN_FAILURE';

export const FORGOT_PASSWORD_REQUEST ='FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_STARTED ='FORGOT_PASSWORD_STARTED';
export const FORGOT_PASSWORD_SUCCESS ='FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE ='FORGOT_PASSWORD_FAILURE';

export const LOOKUP_REQUEST ='LOOKUP_REQUEST';
export const LOOKUP_STARTED ='LOOKUP_STARTED';
export const LOOKUP_SUCCESS ='LOOKUP_SUCCESS';
export const LOOKUP_FAILURE ='LOOKUP_FAILURE';

export const SURVEY_LIST_REQUEST ='SURVEY_LIST_REQUEST';
export const SURVEY_LIST_STARTED ='SURVEY_LIST_STARTED';
export const SURVEY_LIST_SUCCESS ='SURVEY_LIST_SUCCESS';
export const SURVEY_LIST_FAILURE ='SURVEY_LIST_FAILURE';

export const SURVEY_DETAIL_REQUEST ='SURVEY_DETAIL_REQUEST';
export const SURVEY_DETAIL_STARTED ='SURVEY_DETAIL_STARTED';
export const SURVEY_DETAIL_SUCCESS ='SURVEY_DETAIL_SUCCESS';
export const SURVEY_DETAIL_FAILURE ='SURVEY_DETAIL_FAILURE';