export const GET_NEWS ='GET_NEWS';
export const NEWS_RECEIVED ='NEWS_RECEIVED';
export const SIGNUP_REQUEST ='SIGNUP_REQUEST';
export const SIGNUP_USER_STARTED ='SIGNUP_USER_STARTED';
export const SIGNUP_USER_SUCCESS ='SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE ='SIGNUP_USER_FAILURE';