export const SIGNUP_REQUEST ='SIGNUP_REQUEST';
export const SIGNUP_USER_STARTED ='SIGNUP_USER_STARTED';
export const SIGNUP_USER_SUCCESS ='SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE ='SIGNUP_USER_FAILURE';
export const LOGIN_REQUEST ='LOGIN_REQUEST';
export const LOGIN_STARTED ='LOGIN_STARTED';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILURE ='LOGIN_FAILURE';